### ISSUE TITLE
Question about evaulation

### ISSUE THREAD

**Issue by MoonBlvd** [StanfordASL/Trajectron-plus-plus#10]
Hi,

Thank you so much for this great work! 
I have a question for how the model is evaluated on ETH/UCY data groups. Based on your paper, you use 8 past frames as input to predict future 12 frames. However, I have noticed that some of the samples do not have 8 frames and you set those non-exist frames to be NaN. So do you also evaluation Trajectron++ on those short frames? And when you compare with S-GAN or other SOTA method, were those method using the same input as yours?

Thank you!

**Comment by MoonBlvd** [comment]
Also, could you please let me know how did you convert UCY dataset annotations from pixels to meter? I didn't find camera matrix from their original website...

**Comment by BorisIvanovic** [comment]
Hi @MoonBlvd , thank you for your questions and my apologies for the late response, I only saw this now (is there a way to enable email notifications about new issues? I thought it would be by default...)

Regarding your first question, I've dived into this and can confirm that we do evaluate Trajectron++ with these short frames as well. This is actually a mistake :( In the evaluation script I should have also added `min_history_timesteps=8` in the call to Trajectron++'s `predict` function. This change would be made at: https://github.com/StanfordASL/Trajectron-plus-plus/blob/139080c2aeec06dd87b1b93c2f6c813a0d060243/experiments/pedestrians/evaluate.py#L113 and all subsequent calls to `eval_stg.predict(...)`.

The reason I didn't originally have this argument is because I actually thought we were doing this by default inside the https://github.com/StanfordASL/Trajectron-plus-plus/blob/139080c2aeec06dd87b1b93c2f6c813a0d060243/trajectron/model/dataset/preprocessing.py#L66 function, but alas I see https://github.com/StanfordASL/Trajectron-plus-plus/blob/139080c2aeec06dd87b1b93c2f6c813a0d060243/trajectron/model/dataset/preprocessing.py#L93 which allows for short frames (as you correctly pointed out). Thank you for the great catch!

This means that Trajectron++'s results are actually _better_ than the reported values in the paper (we're currently hampering our model by including these short frame inputs). All the other approaches (S-GAN, etc) use exactly 8 previous frames and we use exactly the results they report in their works.

As for how did we convert UCY annotations from pixels to metric, that's a good question, we didn't. I actually have to refer you to the S-GAN codebase for this, since we use their exact same input data. You can download the metric version of the pedestrian datasets there (this is where we got our pedestrian datasets): https://github.com/agrimgupta92/sgan/blob/master/scripts/download_data.sh

**Comment by MoonBlvd** [comment]
Hi @BorisIvanovic, thank you for your detailed reponse! I have the same findings with yours. I tried to set `min_hitory_timesteps=8` in evaluation which gives me better results. I think it's fair to update your paper's table if you are sure that all other competitors are evaluating on 8 inputs frames. In fact, I'm a little confused about this history timesteps. From my observation, the input to the model is actually `8+1=9`, where `8` is the number of past frames and `1` is the current frame. Are you sure that S-GAN and other competitors alsp use `8+1` timesteps as inputs?

As to converting pixel to metrics for UCY, I have seen people posting issues in S-GAN github asking about this but got no response yet...Do you have any suggestions?

**Comment by BorisIvanovic** [comment]
Unfortunately, only the S-GAN codebase is public. I _think_ you're correct and that they use 7 past + 1 current (based on https://github.com/agrimgupta92/sgan/blob/691231e1adb6a344c7bcea9ebf2534518b226ead/sgan/data/trajectories.py#L131), so I think `min_history_timesteps=7` would actually be the value to use here (matching 7 past + 1 current).

Regarding converting pixels to m, does this help? https://github.com/agrimgupta92/sgan/issues/5

**Comment by MoonBlvd** [comment]
@BorisIvanovic  Thank yor pointing me to that sgan issue. The homography matrix given in that issue doesn't seem to be right. But later the author posted this : https://github.com/trungmanhhuynh/Scene-LSTM which seems to be correct!

As to using 8 frames instead of 9, I think you should also set max_history_timesteps=7 so that you are not using 9 frames as input. Is it correct?

**Comment by BorisIvanovic** [comment]
Correct! That's what I refer to with the "as well as changing that corresponding value in the model config files to 7 (from 8)" comment (that sets the max_history_timesteps value).

**Comment by MoonBlvd** [comment]
@BorisIvanovic Great! Please let me know once you update your results, Thank you! :D

**Comment by BorisIvanovic** [comment]
@MoonBlvd Done! The following commit makes the aforementioned changes and updates the results notebook with the latest results (and the diff shows a side-by-side comparison): b05c7b2ba431ae1aaa9218f8d7b9c9b44edff117

You'll see these updates reflected in the next version of the arXiv paper (I don't have an ETA for you, but it will happen).

Feel free to close this issue if this commit is satisfactory to you and all your questions are answered. Thank you again for raising this concern!

**Comment by MoonBlvd** [comment]
@BorisIvanovic Sure! Thank you for clarifying all those issues with me. Congrats on your even better results!
