### ISSUE TITLE
[QUESTION] How can I visualize other scenes?

### ISSUE THREAD

**Issue by lorience** [StanfordASL/Trajectron-plus-plus#18]
Hello,

Thank you for the previous asnwer to my question, since it is closed I didn't want to re-open it.

nuScenes Qualitative notebook seems great thanks for that; however, I couldn't load up other scenes. When I change scenes rendered image is not the way it is supposed to be and this is probably because of the defined
```
# Define ROI in nuScenes Map
x_min = 773.0
x_max = 1100.0
y_min = 1231.0
y_max = 1510.0
```
and

```
ax.set_ylim((1385, 1435))
ax.set_xlim((850, 900))
```

For example, if I want to visualize 
`scene = eval_scenes[20]` instead of `scene = eval_scenes[25]`, How can I find these correct {x,y}_min, {x,y}_max values? I tried to look up the dataset and the environment of the trajectron but I couldnt find. I probably miss some attributes. I would be glad if you can help. 

Btw, I learned a lot while reading through your paper and this github repository. Thanks for publishing such great quality content.

**Comment by lorience** [comment]
I figured that out by finding the position on nuScenes dataset but I would like to know whether environment holds this information as well.

**Comment by BorisIvanovic** [comment]
Hi @lorience,

My apologies for not responding earlier, this week and next are unfortunately quite hectic for me...

Regarding how to get the actual x_min, y_min values from the dataset at inference time, I recommend the following (and it's been what I've been doing myself since publishing this codebase).

1. Change the `Scene` object constructor in `trajectron/environment/scene.py` to the following:
```
class Scene(object):
    def __init__(self, timesteps, map=None, dt=1, name="", frequency_multiplier=1,
                 aug_func=None, non_aug_scene=None, x_min=None, y_min=None):
        self.map = map
        self.timesteps = timesteps
        self.dt = dt
        self.name = name
        self.x_min = x_min  # Used to get predictions back into global coordinates.
        self.y_min = y_min  # Used to get predictions back into global coordinates.

        self.nodes = []

        self.robot = None

        self.temporal_scene_graph = None

        self.frequency_multiplier = frequency_multiplier

        self.description = ""

        self.aug_func = aug_func
        self.non_aug_scene = non_aug_scene
```

2. Change `experiments/nuScenes/process_data.py` to actually feed that information to the `Scene` constructor.

You should change [this line](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/process_data.py#L252) to

```
    scene = Scene(timesteps=max_timesteps + 1, dt=dt, name=str(scene_id), aug_func=augment, x_min=x_min, x_max=x_max)
```

3. Re-run `process_data.py` and then you should see this information in each scene.

I hope this helps!

**Comment by BorisIvanovic** [comment]
As for your second question, we decided upon these "local" positions for each agent (the ones where x_min/y_min were subtracted) because we were initially worried about the prospect of passing in values with large magnitude to the model (positions are frequently around 10^3). We were worried about activation saturation at early iterations (e.g., sigmoid(x) with a very large x will return essentially no gradient), but this was probably us being overly cautious since the positions are still around 10^2 even after x_min/y_min subtraction.

**Comment by lorience** [comment]
``` scene = Scene(timesteps=max_timesteps + 1, dt=dt, name=str(scene_id), aug_func=augment, x_min=x_min, x_max=x_max)```

Should be 

```scene = Scene(timesteps=max_timesteps + 1, dt=dt, name=str(scene_id), aug_func=augment, x_min=x_min, y_min=y_min)```
right?

**Comment by BorisIvanovic** [comment]
Oops, yes. My apologies, I'll correct that now.

**Comment by lorience** [comment]
Is it possible to load the trained model to gpu? As I see it is on cpu.

**Comment by tinmodeHuang** [comment]
hey guys!
did you come across  the case that the following error pops up in that script when running up to the cell "Prediction including Map Encoding".
```
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-120-c36cd443b374> in <module>
     51     ax.get_legend().remove()
     52     fig.show()
---> 53     fig.savefig('plots/qual_nuScenes_map_pos.pdf', dpi=300, bbox_inches='tight')

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/figure.py in savefig(self, fname, **kwargs)
   2033             self.set_frameon(frameon)
   2034 
-> 2035         self.canvas.print_figure(fname, **kwargs)
   2036 
   2037         if frameon:

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2261                 orientation=orientation,
   2262                 bbox_inches_restore=_bbox_inches_restore,
-> 2263                 **kwargs)
   2264         finally:
   2265             if bbox_inches and restore_bbox:

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py in print_pdf(self, filename, **kwargs)
   2576             file = filename._file
   2577         else:
-> 2578             file = PdfFile(filename, metadata=kwargs.pop("metadata", None))
   2579         try:
   2580             file.newPage(width, height)

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/backends/backend_pdf.py in __init__(self, filename, metadata)
    436         self.original_file_like = None
    437         self.tell_base = 0
--> 438         fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
    439         if not opened:
    440             try:

~/.conda/envs/trajectron++/lib/python3.7/site-packages/matplotlib/cbook/__init__.py in to_filehandle(fname, flag, return_opened, encoding)
    607             fh = bz2.BZ2File(fname, flag)
    608         else:
--> 609             fh = io.open(fname, flag, encoding=encoding)
    610         opened = True
    611     elif hasattr(fname, 'seek'):

FileNotFoundError: [Errno 2] No such file or directory: 'plots/qual_nuScenes_map_pos.pdf'
```
and link of the resulting figure is here (https://github.com/tinmodeHuang/autonomous-driving-resource/blob/master/qual_nuScenes_map_pos.pdf)
for solve it, one cell having the following  was put before that cell.
```
if not os.path.exists('plots'):
    os.makedirs('plots')
```
otherwise there weren't any predicted trajectories in the resulting figure, note that  nuScenes "mini" dataset was used here

**Comment by lorience** [comment]
Yeah you had to create that plots directory manually or from the code.

**Comment by tinmodeHuang** [comment]
I have confused about what causes the absence of prediction trajectories in the resulting figure, could you give  me any tips?

**Comment by lorience** [comment]
> I have confused about what causes the absence of prediction trajectories in the resulting figure, could you give me any tips?

If you used nuscenes mini you have only scene[0] and scene[1]. If you try to draw scene[25] it will fail. Also scene[0] and scene[1] may have different x,y coordinates. In the drawing x,y coordinates give extreme values like 0,2500 and see if the projectories are there.

**Comment by BorisIvanovic** [comment]
I'm going to close this out since it seems like the original issue was resolved, please let me know if this is incorrect!

**Comment by tinmodeHuang** [comment]
kdsjf

**Comment by tinmodeHuang** [comment]
> > I have confused about what causes the absence of prediction trajectories in the resulting figure, could you give me any tips?
> 
> If you used nuscenes mini you have only scene[0] and scene[1]. If you try to draw scene[25] it will fail. Also scene[0] and scene[1] may have different x,y coordinates. In the drawing x,y coordinates give extreme values like 0,2500 and see if the projectories are there.

you're right! I find that the ten scenegraphs all were split into two parts in which two scenegraphs serve as an evaluation when I just retry to train the model with the mini database, I successfully use eval_scenes[0] as evaluation while the other , namely eval_scenes[1], failed, which have made me confused.

**Comment by TheSkrill** [comment]
Hey everyone!
@BorisIvanovic  @kaanapan Thanks a million for your solution! I was facing the same problem since the past 2 days.


I have followed all the steps mentioned above, and I successfully got the x_min and the y_min values.
Can anybody please tell me how could we get the x_max and y_max values?
