### ISSUE TITLE
Multi-GPU Training

### ISSUE THREAD

**Issue by os1a** [StanfordASL/Trajectron-plus-plus#23]
Hi,

Could you please give some insights on how to enable the multi-gpu training especially on the nuScenes dataset?

Also any hint to make training faster is very welcome.

Best,
Osama

**Comment by os1a** [comment]
Also a follow-up question:
I am training the nuScenes with all options included (map, dynamics, and robot) on GTX1080Ti, but the training seems to be very slow. Sometimes I got around 70s/it and sometimes I got 1.5s/it

According to your paper, you train on a GTX1080Ti with 2 GPUs and it tooks 8 hours, does it mean that you enable multi-gpu training?

**Comment by os1a** [comment]
Hi,
Increasing the number of workers by setting preprocess_workers to be larger than 0 needs larger CPU memory.
The best configuration I found for training on nuScenes is:
GTX1080Ti, 10 cpus cores, CPU memory 100GB, preprocess_workers = 10
Then the network takes 20 minutes per epoch.

I will close this issue since I found a feasible solution, but please feel free to write more information if you think training on multiple GPUs could help.

**Comment by BorisIvanovic** [comment]
Hi @os1a, we actually didn't use Multi-GPU training, our big speedup came from parallel data loading (which you've discovered yourself here). I'm sorry that this wasn't more explicitly stated in the README.

Also, it is expected that adding the map encoding takes more time (because of the CNN as well as the larger memory needs from handling map images). I actually think 20 minutes exactly matches the runtime we had (you and I have the exact same GPUs, although my desktop "only" has 64 GBs of CPU RAM).
