### ISSUE TITLE
question about online model

### ISSUE THREAD

**Issue by minanoo** [StanfordASL/Trajectron-plus-plus#24]
HI, Thanks for your nice work 
I have some question about the online model as [paper](https://arxiv.org/pdf/2008.03880.pdf) mentioned.
Is test_online.py the model using online? If it is, could you help me to use it since there is no readme.If not, could you give me insight into online model?

**Comment by BorisIvanovic** [comment]
Hi @minanoo , thanks for asking!

I actually haven't publicly released that part of the code yet, you're right that `test_online.py` is using the online version of the model, but I haven't thoroughly tested it like the other parts of the code so I'm not ready to release it just yet, I'm sorry about that!

As for insights, sure! The whole point of the "online" version of the model is to take the trained trajectory forecasting model but enable it to be run on streaming data (i.e., to be used online in the real-world). What does that mean? It means that this version of the model only needs to be fed observed trajectory information at the current timestep to make predictions for the future (it internally keeps track of the previously-observed information). This is much faster than running the full model always because you only need to update a few LSTM cells in the encoder before running the decoder (compared to re-encoding the whole observed trajectories every time). The idea I had for this model is that it would be the actual version used by practitioners on robots since it's faster than the current version of the model which is optimized for batch training (as most things in deep learning are).

Does that give you more insight? Please let me know if you have further questions!

**Comment by minanoo** [comment]
Thanks for replying!
I got it and looking forward to the release code.

**Comment by BorisIvanovic** [comment]
Heading information is necessary for the any of the models (if you want to use our pre-trained versions). However, I don't think it should be that hard to obtain heading information from velocity, right? For example: heading = arctan2(v_y, v_x)

**Comment by minanoo** [comment]
Got it Thanks!!!

**Comment by BorisIvanovic** [comment]
174198bd4f2119c4d9b440de482b64e3b8ad1719 has now added this functionality!
