### ISSUE TITLE
Question about model selection on the ETH/UCY datasets

### ISSUE THREAD

**Issue by YuejiangLIU** [StanfordASL/Trajectron-plus-plus#38]
Thanks for sharing the code of your great work.

From the [provided commands](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/README.md#pedestrian-dataset) and the [pre-trained models](https://github.com/StanfordASL/Trajectron-plus-plus/tree/master/experiments/pedestrians/models), it looks like all training processes on the ETH/UCY datasets are terminated at the 100th epoch. 

When using your code, shall we simply pick the last checkpoint to test or we'd better go through all checkpoints saved during training? Was the validation set used in model selection?

Thanks

**Comment by BorisIvanovic** [comment]
Hi @YuejiangLIU, thanks for the great questions! 

We specifically chose the 100th epoch because the losses more or less flattened out by that point and the performance on the validation set didn't look as if it was going to improve further (we looked at the validation set just to make sure we weren't leaving tons of performance on the table, but yeah our hyperparameter tuning was pretty light overall). 

Sure, we likely could have stopped training earlier and obtained similar (maybe even better) performance, but:

1. The performance of the models was already fine at that point, and
2. We didn't want to hyperparameter optimize ad nauseum, so we just trained all of the models to the same point with similar hyperparameters.

It's a balancing act: one could probably get better performance with more hyperparameter tuning/earlier stopping/etc, but at the end of the day we figured the performance gains would have been marginal and not really worth the added time investment.

For your personal use case, I'd say it's up to you. If you're looking to absolutely maximize performance then feel free to pick the best training iteration per model, otherwise I wouldn't worry about it and feel that 100 epochs is fine.

**Comment by YuejiangLIU** [comment]
Thanks a lot for your detailed response!

Just wanted to ask a follow-up question regarding the experimental results. I've been trying to validate a [contrastive method on top of your model](https://github.com/YuejiangLIU/social-nce-trajectron-plus-plus). To have a clean and reproducible comparison, I'd hope to make the training as deterministic as possible.

However, the variance of experimental results seems persistent and perceptible on different machines. When using a fixed random seed, I constantly see identical results across multiple runs on the same machine, but different values (~10%) of ADE/FDE on different machines. Have you come across the same issue before?

I've tried the tips in the official [PyTorch Reproducibility docs](https://pytorch.org/docs/1.8.1/notes/randomness.html). 

- The [torch.use_deterministic_algorithms()](https://pytorch.org/docs/stable/notes/randomness.html) / [torch.set_deterministic()](https://pytorch.org/docs/1.7.1/notes/randomness.html) is unfortunately not applicable in the current code base, as it triggers 'RuntimeError: index_add_cuda_ does not have a deterministic implementation'. 
- The rest tips do not resolve the issue.

If I understand correctly, the current code does not explicitly call the 'index_add_()' method. Do you know if there is any part of the code that may have used the 'index_add_()' at a lower level?

**Comment by BorisIvanovic** [comment]
First of all, very glad to see that you're building on top of our work! 

Unfortunately, I have only been using one machine to develop Trajectron++ so constantly seeing identical results across multiple runs on the same machine is my experience based on my hardware setup. Sorry that I don't have more advice to give along this direction :(

Regarding index_add_(), I'm certain we don't call that explicitly in the code. Unfortunately, I also don't know a lot of the internal algorithms used within PyTorch, my first thought would be to search the actual [PyTorch codebase](https://github.com/pytorch/pytorch) for mentions of `index_add_` and maybe that will shed some light on what component could be using it within our model?

**Comment by YuejiangLIU** [comment]
Thanks again @BorisIvanovic for your timely and helpful reply! I'll have a deeper search of this `index_add_ `operation in the source code then. Thanks!
