### ISSUE TITLE
Questions regarding the cost function

### ISSUE THREAD

**Issue by Mirorrn** [StanfordASL/Trajectron-plus-plus#41]
Hello @BorisIvanovic ,

I have little experience with CVAE and do not fully understand the prior network p_\theta(z|x), which is trained in the Trajectron as well as in the Trajectron++. In DESIRE as well as other CVAE approaches, p(z|x) is assumed to be N(0,I) and is not dependent on X.  Thus, the term KL(q(z|x,y) || N(0,I)) is given a fixed target for the ELBO. As far as I understand it correctly, p_\theta(z|x) is only trained over KL(q(z|x,y) || p_\theta(z|x)) in the case of the Trajectron, so we (hopefully) get p_\theta(z|x) = q(z|x,y).  Does this lead to unstable training, since q(z|x,y) and p_\theta(z|x) are trained simultaneously? 

In Trajectron++, p_\theta(z|x) is additionally trained using the mutual information, which brings us to my 2nd question. In the InfoVAE paper, in addition to the ELBO cost function, the term D(q_{phi}(z) || p(z)) comes into play, which can be determined with the Maximum-Mean Discrepancy, for example. Why do you calculate the mutual information H(z)-H(z|x) over p_\theta(z|x) instead?

Many greetings
Mirorrn

**Comment by BorisIvanovic** [comment]
Hello @Mirorrn ,

1. Good question! It might lead to unstable training if you don't have any kind of weighting of the cost function terms. However, in this work we use beta in the loss function (Eq. 4) to help us. As we describe in Appendix D.1, beta increases during training so that at the early iterations of learning, when the model is not particularly good, most of the loss function's value comes from the first term (the log-likelihood). In later iterations, when the model performs better, beta gradually increases and more of the loss function's value comes from the D_KL term which forces the model to transfer the role of encoding the input from q (which by now should be performing well) to p (which still needs to be trained well).
2. We only wanted to add the mutual information term to the loss function to encourage the model to use the latent variable during online inference (rather than relying purely on the y in q during training). As you know, we calculated the mutual information H(z)-H(z|x) over p_\theta(z|x) to do this, as maximizing this encourages the model to use the latent variable.

**Comment by Mirorrn** [comment]
Hallo @BorisIvanovic,

thank you for the quick and informative response!

Best regards

**Comment by BorisIvanovic** [comment]
Kein Problem, viel Glück!
