### ISSUE TITLE
ImportError: cannot import name 'block_diag'

### ISSUE THREAD

**Issue by mincheulkim** [StanfordASL/Trajectron-plus-plus#44]
Hi, thanks to your great work, but unfortunately i'm having trouble implementing your code.

When I tried to run 'python process_data.py' at data setup stage, the machine show below conflict.

File "process_data.py", line 9, in <module> from environment import Environment, Scene, Node
...skip few lines...
File "/home/Trajectron-plus-plus/trajectron/model/dynamics/single_integrator.py", line 3, in <module>
    from utils import block_diag
ImportError: cannot import name 'block_diag'

How can I solve this issue? thanks!

**Comment by BorisIvanovic** [comment]
Hi @mincheulkim 

Interesting... I can see the function here: https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/utils/matrix_utils.py#L12

I wonder if it might be because you are not including a line like `sys.path.append("../../trajectron")` at the top of the script (since `utils` is within `trajectron/...` and not within the experiments folder). Could you please check that it is there?
