### ISSUE TITLE
How to choose attention_radius?

### ISSUE THREAD

**Issue by Xiejc97** [StanfordASL/Trajectron-plus-plus#60]
Hi,

Thanks for your good job. I want to ask how you choose attention_radius for the ETH/UCY and Nuscenes dataset?
I find that when you use ETH/UCY dataset, you set `attention_radius[(env.NodeType.PEDESTRIAN, env.NodeType.PEDESTRIAN)] = 3.0` in https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/pedestrians/process_data.py#L89. 

While  you use Nuscenes dataset, you set `attention_radius[(env.NodeType.PEDESTRIAN, env.NodeType.PEDESTRIAN)] = 10.0
        attention_radius[(env.NodeType.PEDESTRIAN, env.NodeType.VEHICLE)] = 20.0
        attention_radius[(env.NodeType.VEHICLE, env.NodeType.PEDESTRIAN)] = 20.0
        attention_radius[(env.NodeType.VEHICLE, env.NodeType.VEHICLE)] = 30.0` in https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/process_data.py#L417.

Do you have any requirements for the setting of this attention radius? If I change to my own dataset, how much should I set this attention radius?

Best

**Comment by BorisIvanovic** [comment]
Hi @Xiejc97, sorry for my late response. I hope the following helps!

There's no "one true rule" to these values, they should be viewed as hyperparameters. I chose the attention radii the first time around based mostly around what I thought would be reasonable estimates for the respective datasets (e.g., based on scene density and visibility). Now, these will also naturally affect your computation times and memory usage (since they directly affect the number of edges resulting in the scene graph), so that may also play a role depending on your computational resources.

If you're applying this method to your own dataset, thinking about what kind of visibility each agent has of others and at what distances agents may influence each other (e.g., drivers on a highway naturally look much farther ahead than pedestrians on a sidewalk) is a good starting point, and this was the idea I had in my head when I first chose these.
