### ISSUE TITLE
test_online；The output image does not contain map information.

### ISSUE THREAD

**Issue by 76qian** [StanfordASL/Trajectron-plus-plus#62]
Dear author,
I have recently been reproducing your paper "Trajectron++: Dynamically-Feasible Trajectory Forecasting With Heterogeneous Data". After running test_online.py, the output PDF file contains only the vehicle tracks and no map information, as shown below. But I'm sure I chose a run method that includes map manipulation. I am very confused about this, so I want to consult you. If you have the final version of test_online.py or other advice, could you please send it to me?
<img width="519" alt="08F5CB41-D7A6-449C-AF23-ABC2202EC049" src="https://user-images.githubusercontent.com/96508781/161685181-9b904894-57c2-4d70-b174-2f4596601aea.png">

**Comment by BorisIvanovic** [comment]
Dear Jia,

Thanks for reaching out. The reason the map is not plotted is because I did not add map plotting to that part of the code, as can be seen [here in test_online.py](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/test_online.py#L204)

Feel free to add map plotting code if you would like to! For inspiration as to how, the training script contains some examples, e.g., [here in train.py](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/train.py#L307)

Thanks!
Boris

**Comment by xiaoyaocoding** [comment]
Thank you for your excellent work, but I'm a little confused about the meaning of the red line segment in the figure, could you please explain it to me？
![image](https://user-images.githubusercontent.com/102663190/232266793-b834cee3-bde1-4519-8d09-94f511ba617a.png)

**Comment by BorisIvanovic** [comment]
As can be seen in [this line](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/trajectron/test_online.py#L219), the ego-vehicle's future trajectory is colored red.
