### ISSUE TITLE
Step annealing params and KL value

### ISSUE THREAD

**Issue by mvignaga** [StanfordASL/Trajectron-plus-plus#85]
Hi Boris,

I printed KL and KL_Weight to check their value against the ELBO.
It seems that KL_Weight reaches the maximum value (100) quite early in the epoch (around 10% completed) so I wanted to ask you why are you updating its value this fast and if it shouldn't be updated outside the epoch loop, to gradually reach the maximum epoch by epoch.

Also I found that value for the KL is not increasing above its min value of 0.07 in the first epoch. Shouldn't it to grow faster with a KL_Weight=100?

I'm using NuScenes mini dataset. 

Thank you for your time and your work.
Marco

**Comment by BorisIvanovic** [comment]
> if it shouldn't be updated outside the epoch loop, to gradually reach the maximum epoch by epoch

You could definitely try this! 

As for why we chose the switchover points we did, we found that making the switchover take too long makes the model ignore some of the conditioning inputs (especially the map input, since the map part of the model trains slower than the recurrent encoder part of the model). 

Of course, you can experiment with this, and see if it works better for your usecase, but we found that these schedules worked alright and we didn't need to tune them much more once we found a set of settings that works.
