### ISSUE TITLE
Non-moving vehicle track length (does it cause bias?)

### ISSUE THREAD

**Issue by dthuremella** [StanfordASL/Trajectron-plus-plus#89]
Hi Boris,

Thank you for your work and up-to-date repository; it's been a great help in my research.

I have one question about your data processing script for nuscenes (process_data.py):  
When the velocity of a vehicle is close to 0 (i.e. where you've put the comment "# vehicle is "not" moving"), it seems that you repeat the first x and y coordinate for the length of max_timesteps (full length of the scene) instead of for the length of time that the vehicle is visible in the scene. Why is this the case, and does it influence the results one way or another?

Thank you for taking the time,
Divya

**Comment by BorisIvanovic** [comment]
Hi Divya,

This is more a quirk of the nuScenes dataset. When we were doing our initial dataset explorations, we saw that there can be a lot of noise/small-scale motion for stationary vehicles (because they are hand-annotated per keyframe). Accordingly, we didn't want T++ to reproduce small noisy motion for stationary vehicles, so we chose a threshold for `pl` (it stands for path length) and if a vehicle doesn't move over the entire length of its observation more than some value then we say it's stationary and force it to be stationary.

As for why the length of the scene vs its observation? Our thinking was that this vehicle is stationary and exists within the scene, even if it's only observed for part of it. Of course, this may not hold universally true, but there are _a lot_ of parked cars in nuScenes so this almost universally holds true.

I don't believe this will influence results much since prediction models aren't really asked to predict stationary vehicles. Of course, you can remove those lines, but be warned that it may cause T++ (or any other of your favorite models) to predict noisy motion for stationary vehicles.

**Comment by dthuremella** [comment]
Hi, 

Thanks for your response - I have one further question, if you don't mind:
Why do you you say that this won't influence results, and that prediction models aren't asked to predict stationary vehicles? Is there something in the code that ignores prediction of vehicles which are stationary? And if so, could you point me to where that is?

Thanks,
Divya

**Comment by BorisIvanovic** [comment]
Nothing in the T++ code itself, but prediction datasets themselves (e.g., the agents that are chosen by prediction datasets to be predicted are not typically stationary)

**Comment by dthuremella** [comment]
Ah I see, thank you. Presumably, it does influence results slightly by creating more stationary tracks: an experiment in changing max_timesteps to len(x) (keeping the track length of stationary vehicles the same as the length of their observation) causes the FDE of vehicles @3s to be 1.28 instead of 1.14

Do you think this could be causing a slight bias towards predicting vehicles to be stationary, since it sees more of that in the dataset than are there?
